# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
# 
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- mode: ruby -*-
# vi: set ft=ruby :

$dockerize = <<EOF
    apt-get update
    apt-get install -y docker.io
    ln -sf /usr/bin/docker.io /usr/local/bin/docker
    sed -i '$acomplete -F _docker docker' /etc/bash_completion.d/docker.io
    source /etc/bash_completion.d/docker.io
    chmod 777 /var/run/docker.sock

    echo -e "\n#Dockerize\nbash /deploy/supervisor/up.sh" >> ~/.bash_rc
    # Magic
    #echo -e '#!/bin/bash\nbash /deploy/supervisor/up.sh' > /usr/local/bin/supervisor
    #chmod +x /usr/local/bin/supervisor
    #chsh -s /usr/local/bin/supervisor vagrant
EOF

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/trusty64"

    config.vm.synced_folder "..", "/deploy/"

    config.vm.hostname = "supervisor"

    config.vm.network :private_network, ip: "10.100.100.254", netmask: "255.255.0.0"

    config.vm.provider :virtualbox do |vb|
        vb.name = "supervisor_#{Time.now.to_i}"
        vb.customize ["modifyvm", :id, "--memory", "1024"]
    end

    config.vm.provision :shell, inline: $dockerize
end
